from __future__ import annotations

from typing import Any


def lesson(
    lesson_id: str,
    title: str,
    *,
    duration_min: int,
    difficulty: str,
    summary: str,
    theory: str,
    practical: list[str],
    mistakes: list[str],
    app_links: list[dict[str, str]],
    case_study: str | None = None,
    why_it_matters: str | None = None,
    framework: list[str] | None = None,
    app_exercise: list[str] | None = None,
    checklist: list[str] | None = None,
    before_continue: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "id": lesson_id,
        "title": title,
        "duration_min": duration_min,
        "difficulty": difficulty,
        "summary": summary,
        "theory": theory,
        "practical": practical,
        "mistakes": mistakes,
        "case_study": case_study or "",
        "app_links": app_links,
        "why_it_matters": why_it_matters or "",
        "framework": framework or [],
        "app_exercise": app_exercise or [],
        "checklist": checklist or [],
        "before_continue": before_continue or [],
    }


def indicator(
    indicator_id: str,
    name: str,
    *,
    formula: str,
    interpretation: str,
    works_when: str,
    fails_when: str,
    strategy_use: str,
    common_mistakes: list[str],
    example: str,
) -> dict[str, Any]:
    return {
        "id": indicator_id,
        "name": name,
        "formula": formula,
        "interpretation": interpretation,
        "works_when": works_when,
        "fails_when": fails_when,
        "strategy_use": strategy_use,
        "common_mistakes": common_mistakes,
        "example": example,
    }


APP_CTA_BUILDER = {"label": "Usa nel builder", "href": "/builder"}
APP_CTA_DESK = {"label": "Monitora sul desk", "href": "/dashboard"}
APP_CTA_WORKSPACE = {"label": "Apri workspace", "href": "/workspace"}


INDICATOR_LIBRARY = [
    {
        "id": "trend-following",
        "title": "Trend following",
        "description": "Segnali che funzionano quando il mercato sviluppa persistenza direzionale e volatilità ordinata.",
        "indicators": [
            indicator(
                "ema",
                "Exponential Moving Average (EMA)",
                formula="EMA_t = alpha * prezzo_t + (1-alpha) * EMA_{t-1}",
                interpretation="Filtra il rumore e dà più peso ai prezzi recenti. È utile come filtro direzionale o come base per crossover.",
                works_when="Trend puliti, mercati con persistenza, orizzonti intraday o swing dove il rumore non domina.",
                fails_when="Laterali stretti, improvvisi mean reversion, accelerazioni con gap e compressione di volatilità.",
                strategy_use="Filtro trend, crossover veloce/lento, pullback in trend, regime classification.",
                common_mistakes=[
                    "Usarla da sola come trigger senza filtro di regime.",
                    "Ottimizzare troppo i periodi fino a catturare solo il passato.",
                    "Ignorare che un crossover arriva già con ritardo.",
                ],
                example="In un bot FX, usa EMA 20 sopra EMA 50 per abilitare solo segnali long su breakout di massimi di sessione.",
            ),
            indicator(
                "macd",
                "MACD",
                formula="MACD = EMA veloce - EMA lenta; Signal = EMA del MACD",
                interpretation="Misura accelerazione del trend, non solo direzione. È utile per capire se il momentum trend sta salendo o esaurendosi.",
                works_when="Trend maturi ma ancora ordinati, mercati dove il cambio di slope anticipa la continuation.",
                fails_when="Range sporchi con continui micro swing, asset con spike e mean reversion violenta.",
                strategy_use="Conferma di trend, filtro su breakout, uscita quando il momentum si appiattisce.",
                common_mistakes=[
                    "Entrare a ogni cross del signal line.",
                    "Usarlo su timeframe troppo bassi senza filtro spread/slippage.",
                    "Confondere divergenza visiva con edge statistico.",
                ],
                example="Su indici, usa MACD histogram > 0 per confermare long breakout solo nelle aperture ad alta espansione.",
            ),
            indicator(
                "donchian",
                "Donchian Channel",
                formula="Upper = max(high, n); Lower = min(low, n)",
                interpretation="Trasforma il prezzo in una misura di breakout: se il mercato rompe il canale, qualcosa è cambiato nella struttura recente.",
                works_when="Mercati trend-following, futures, FX majors durante fasi espansive o post-news.",
                fails_when="Mercati compressi dove il breakout è continuamente riassorbito.",
                strategy_use="Breakout systems, stop trailing, regime expansion detection.",
                common_mistakes=[
                    "Usare lo stesso lookback su tutti gli asset.",
                    "Non distinguere tra breakout overnight e breakout in-session.",
                    "Non testare l'impatto delle false rotture.",
                ],
                example="Canale 20 barre come trigger; entra solo se ATR è in aumento e il volume è sopra la media.",
            ),
            indicator(
                "adx",
                "ADX",
                formula="Derivato da +DI e -DI per misurare la forza del trend",
                interpretation="Non dice la direzione, ma quanta energia c'è nel movimento. Ottimo come filtro trend/no-trend.",
                works_when="Vuoi separare trend forte da mercato rumoroso prima di attivare altri segnali.",
                fails_when="Cambi di regime rapidi dove la forza sale troppo tardi rispetto al movimento iniziale.",
                strategy_use="Gating layer: attiva breakout o momentum solo sopra una soglia ADX.",
                common_mistakes=[
                    "Leggerlo come segnale di entry autonomo.",
                    "Usare soglie fisse senza guardare asset/timeframe.",
                ],
                example="Se ADX < 18, disattiva trend-following e passa a modelli mean reversion o resta flat.",
            ),
        ],
    },
    {
        "id": "mean-reversion",
        "title": "Mean reversion",
        "description": "Indicatori utili quando i prezzi oscillano intorno a un fair value locale e i movimenti estremi tendono a chiudersi.",
        "indicators": [
            indicator(
                "rsi",
                "RSI",
                formula="RSI = 100 - 100 / (1 + RS)",
                interpretation="Misura la velocità del movimento. Più che overbought/oversold, indica eccesso relativo nella finestra osservata.",
                works_when="Mercati range, reversion intraday, asset con forte inventory rebalancing.",
                fails_when="Trend forti e persistenti dove l'eccesso resta e continua.",
                strategy_use="Mean reversion su pullback, filtro per evitare entry chasing, conferma di esaurimento.",
                common_mistakes=[
                    "Shortare automaticamente sopra 70 in trend rialzista.",
                    "Non combinare RSI con contesto di trend o volatilità.",
                    "Usarlo con periodi iper-ottimizzati.",
                ],
                example="Su EURUSD range, entra long solo quando RSI < 25 vicino al bordo inferiore di una banda statistica.",
            ),
            indicator(
                "bollinger-bands",
                "Bollinger Bands",
                formula="MA ± k * deviazione standard",
                interpretation="Mostra distanza del prezzo dalla media in unità di volatilità recente.",
                works_when="Mercati mean reverting o fasi di compressione con ritorno verso la media.",
                fails_when="Breakout reali con volatilità che si espande e prezzo che cavalca la banda.",
                strategy_use="Fade degli estremi, squeeze setup, trailing in mercati compressi.",
                common_mistakes=[
                    "Vendere ogni tocco banda superiore.",
                    "Ignorare la direzione del trend superiore.",
                    "Usare solo le bande senza testare la qualità del ritorno alla media.",
                ],
                example="Compra ritorni verso la media solo quando la chiusura rientra dentro le bande dopo un falso breakout.",
            ),
            indicator(
                "z-score",
                "Z-Score del prezzo o dello spread",
                formula="(x - media) / deviazione standard",
                interpretation="Normalizza l'allontanamento dal fair value. È uno dei segnali più chiari per pair trading e mean reversion statistica.",
                works_when="Spread stazionari, mercati con struttura di ritorno alla media, pair o basket.",
                fails_when="Serie non stazionarie, regimi che cambiano la media in modo permanente.",
                strategy_use="Pair trading, residual trading, mean reversion cross-asset.",
                common_mistakes=[
                    "Applicarlo a serie con trend strutturale.",
                    "Confondere z-score alto con edge garantito.",
                ],
                example="Apri la posizione solo se z-score > 2 e half-life stimata resta sotto una soglia coerente.",
            ),
        ],
    },
    {
        "id": "momentum",
        "title": "Momentum",
        "description": "Segnali che misurano velocità relativa e continuazione del movimento.",
        "indicators": [
            indicator(
                "roc",
                "Rate of Change (ROC)",
                formula="ROC = prezzo_t / prezzo_{t-n} - 1",
                interpretation="Misura performance percentuale recente. Più pulito di molti oscillatori quando vuoi ranking o momentum assoluto.",
                works_when="Trend forti e ranking cross-sectional.",
                fails_when="Mercati whipsaw con rotazioni frequenti.",
                strategy_use="Ranking di asset, momentum assoluto, filtri continuation.",
                common_mistakes=[
                    "Usare finestre troppo brevi e rumorose.",
                    "Non distinguere momentum di trend da spike news-driven.",
                ],
                example="Seleziona i 3 cross FX con ROC 20 giorni più alto e filtra per volatilità sotto controllo.",
            ),
            indicator(
                "stochastic",
                "Stochastic Oscillator",
                formula="(Close - LowestLow) / (HighestHigh - LowestLow)",
                interpretation="Posiziona il prezzo all'interno del range recente. Utile per leggere accelerazione e perdita di impulso.",
                works_when="Mercati range o come trigger secondario dentro trend pullback.",
                fails_when="Breakout strutturali dove il prezzo resta a lungo in ipercomprato/ipervenduto.",
                strategy_use="Trigger di timing per continuation o mean reversion, mai come unico motore.",
                common_mistakes=[
                    "Usarlo come segnale assoluto indipendente dal regime.",
                    "Sovrapporlo a RSI e credere di avere due segnali indipendenti.",
                ],
                example="In trend rialzista, aspetta che Stochastic torni sopra 20 per comprare un pullback e non inseguire massimi.",
            ),
            indicator(
                "percentile-breakout",
                "Percentile Breakout",
                formula="Prezzo rispetto al percentile dei rendimenti o dei range recenti",
                interpretation="Trasforma il breakout in misura statistica, non solo visiva.",
                works_when="Strategie trend systematic o breakout su futures e indici.",
                fails_when="Fasi di compressione senza follow-through.",
                strategy_use="Trigger breakout con soglia minima di eccezionalità statistica.",
                common_mistakes=[
                    "Usare percentile senza considerare il contesto di volatilità.",
                    "Non controllare quanto spesso quel percentile produce false partenze.",
                ],
                example="Attiva un long solo se il breakout giornaliero supera il 90° percentile dei range degli ultimi 60 giorni.",
            ),
        ],
    },
    {
        "id": "volatility",
        "title": "Volatility",
        "description": "Misure di ampiezza e compressione utili per sizing, gating e scelta del regime.",
        "indicators": [
            indicator(
                "atr",
                "Average True Range (ATR)",
                formula="Media del True Range",
                interpretation="Misura ampiezza recente, non direzione. È uno dei mattoni più utili per sizing e stop adattivi.",
                works_when="Quasi sempre, come misura di rischio locale e comparazione di stati di mercato.",
                fails_when="Se usato come segnale direzionale o senza normalizzarlo rispetto al prezzo.",
                strategy_use="Stop, take profit, position sizing, filtri di regime.",
                common_mistakes=[
                    "Usarlo come edge diretto invece che come controllo rischio.",
                    "Mescolare ATR assoluto tra asset con prezzi molto diversi senza normalizzazione.",
                ],
                example="Stop = 1.5 * ATR, trade size regolata per tenere costante il rischio monetario per trade.",
            ),
            indicator(
                "realized-vol",
                "Realized Volatility",
                formula="Deviazione standard dei rendimenti annualizzata",
                interpretation="Misura quanta dispersione sta realmente esprimendo il prezzo.",
                works_when="Regime detection, confronto pre/post evento, allocazione rischio multi-strategy.",
                fails_when="Finestre troppo corte o rumorose senza smoothing.",
                strategy_use="Selezione regime, budgeting rischio, confronto con implied vol.",
                common_mistakes=[
                    "Cambiare strategia su spike di un solo giorno.",
                    "Non distinguere vol trendante da vol compressa in risalita.",
                ],
                example="Se la realized vol passa dal quartile basso a quello alto, riduci sizing e rivedi i filtri breakout.",
            ),
            indicator(
                "parkinson",
                "Parkinson Volatility",
                formula="Basata sul range high-low invece che sui close-to-close return",
                interpretation="È più efficiente quando il range intra-bar è informativo.",
                works_when="Asset liquidi dove high/low portano più informazione dei soli close.",
                fails_when="Serie con gap forti o strumenti dove high/low sono poco affidabili.",
                strategy_use="Confronto di regime, scelta di stop, clustering di vol.",
                common_mistakes=[
                    "Usarla su dati sporchi o sintetici.",
                    "Ignorare l'effetto dei gap.",
                ],
                example="Usa Parkinson vol per distinguere compressione vera da semplice assenza di movimento sui close.",
            ),
        ],
    },
    {
        "id": "volume",
        "title": "Volume-based",
        "description": "Segnali che usano partecipazione e intensità per confermare o invalidare un setup.",
        "indicators": [
            indicator(
                "obv",
                "On-Balance Volume",
                formula="Somma cumulata del volume firmato dalla direzione della candela",
                interpretation="Prova a misurare accumulazione o distribuzione dietro al prezzo.",
                works_when="Asset con volume affidabile, equity, futures, crypto liquida.",
                fails_when="FX spot puro o dati volume di bassa qualità.",
                strategy_use="Conferma breakout, divergences, partecipazione del trend.",
                common_mistakes=[
                    "Usarlo su mercati senza volume reale.",
                    "Interpretare ogni divergenza come reversal certo.",
                ],
                example="Valida un breakout solo se OBV rompe il suo massimo recente insieme al prezzo.",
            ),
            indicator(
                "vwap-deviation",
                "VWAP Deviation",
                formula="Prezzo - VWAP, normalizzato per volatilità",
                interpretation="Misura quanto il prezzo è lontano dal fair value intraday partecipato.",
                works_when="Intraday su strumenti liquidi e session-bound.",
                fails_when="Mercati con bassa partecipazione o multi-session discontinui.",
                strategy_use="Mean reversion intraday, execution benchmark, fade degli eccessi.",
                common_mistakes=[
                    "Applicarlo su timeframe troppo alti come se fosse universale.",
                    "Ignorare la sessione di riferimento del VWAP.",
                ],
                example="In sessione europea, vendi estensioni sopra +2 deviazioni VWAP solo se il trend higher timeframe è neutro.",
            ),
        ],
    },
    {
        "id": "order-flow",
        "title": "Order flow (concettuale)",
        "description": "Sezione concettuale per capire dinamiche di aggressione e assorbimento, anche quando il dato non è direttamente disponibile nell’app.",
        "indicators": [
            indicator(
                "imbalance",
                "Bid/Ask Imbalance",
                formula="Volume aggressivo buy / sell o profondità sbilanciata",
                interpretation="Misura squilibrio immediato tra aggressori e passivi.",
                works_when="Mercati con order book o footprint affidabile.",
                fails_when="Dati aggregati OHLC senza microstruttura reale.",
                strategy_use="Timing di entry, conferma breakout, filtro execution.",
                common_mistakes=[
                    "Trattarlo come edge standalone senza contesto.",
                    "Applicare concetti di order flow su feed che non li supportano davvero.",
                ],
                example="Se il breakout di un massimo avviene con imbalance positivo e nessun assorbimento visibile, il follow-through ha più probabilità.",
            ),
            indicator(
                "absorption",
                "Absorption",
                formula="Prezzo fermo nonostante aggressione elevata su un livello",
                interpretation="Segnala presenza di liquidità passiva che assorbe ordini aggressivi.",
                works_when="Mercati futures/order book con profondità leggibile.",
                fails_when="OHLC puro o market replay approssimativo.",
                strategy_use="Reversal locale, stop placement, invalidation dei breakout.",
                common_mistakes=[
                    "Confondere low volume con assorbimento.",
                    "Usarlo senza verificare il contesto strutturale.",
                ],
                example="Un breakout che viene assorbito sul livello chiave spesso è più informativo di un semplice falso breakout visivo.",
            ),
        ],
    },
    {
        "id": "market-structure",
        "title": "Market structure",
        "description": "Segnali che leggono forma e organizzazione del prezzo, non solo indicatori derivati.",
        "indicators": [
            indicator(
                "swing-structure",
                "Swing High / Swing Low",
                formula="Sequenza di massimi e minimi relativi",
                interpretation="È il linguaggio nativo del mercato: trend, compressione, rottura di struttura.",
                works_when="Tutti i mercati, se formalizzato bene.",
                fails_when="Quando viene definito in modo ambiguo o troppo discrezionale.",
                strategy_use="Trend logic, break of structure, invalidation, trailing.",
                common_mistakes=[
                    "Definizioni troppo vaghe dei pivot.",
                    "Ricostruzioni look-ahead dei massimi/minimi.",
                ],
                example="Definisci swing con fractal o lookback fisso e usa la rottura dell’ultimo swing high come evento codificabile.",
            ),
            indicator(
                "opening-range",
                "Opening Range",
                formula="Massimo/minimo dei primi n minuti di sessione",
                interpretation="Trasforma l’apertura in un regime decisionale: espansione, failure o reversion.",
                works_when="Indici, futures, forex session-driven.",
                fails_when="Mercati con aperture poco significative o liquidi 24/7 senza sessione centrale.",
                strategy_use="Breakout di apertura, fade della failure, filtro sessione.",
                common_mistakes=[
                    "Usare sempre la stessa finestra di apertura.",
                    "Ignorare news macro nei primi minuti.",
                ],
                example="Long solo sopra l’opening range high se volume e volatilità confermano la rottura.",
            ),
        ],
    },
    {
        "id": "statistical-signals",
        "title": "Statistical signals",
        "description": "Segnali per chi vuole trattare il mercato come processo stocastico e non solo grafico.",
        "indicators": [
            indicator(
                "cointegration-zscore",
                "Cointegration Z-Score",
                formula="Z-score del residual tra serie cointegrate",
                interpretation="È un segnale forte quando il rapporto tra serie è stabile e testato.",
                works_when="Pair trading o spread trading con relazione robusta.",
                fails_when="Relazione instabile o rottura strutturale del pair.",
                strategy_use="Entry/exit su spread, sizing in funzione della deviazione.",
                common_mistakes=[
                    "Saltare il test di cointegrazione.",
                    "Usare pair solo perché “si muovono insieme”.",
                ],
                example="Long spread solo se z-score < -2 e il half-life del residual resta compatibile con l’holding period.",
            ),
            indicator(
                "hurst",
                "Hurst Exponent",
                formula="Misura di persistenza o anti-persistenza",
                interpretation="Aiuta a capire se una serie tende più a trendare o revertare nel periodo studiato.",
                works_when="Regime classification su orizzonti abbastanza stabili.",
                fails_when="Finestre troppo corte o serie altamente non stazionarie.",
                strategy_use="Scelta tra modelli trend e mean reversion.",
                common_mistakes=[
                    "Usarlo come trigger di trade.",
                    "Ignorare la sua instabilità al cambiare della finestra.",
                ],
                example="Se Hurst scende sotto 0.45, riduci il peso dei modelli trend-following e testa setup di reversion.",
            ),
        ],
    },
    {
        "id": "alternative-data",
        "title": "Alternative data",
        "description": "Dati non tradizionali o di contesto che possono migliorare regime e filtro rischio.",
        "indicators": [
            indicator(
                "macro-surprise",
                "Macro Surprise Score",
                formula="Valore effettivo - consenso, normalizzato",
                interpretation="Misura lo shock informativo, non solo l’evento in sé.",
                works_when="FX, indici, rates e strategie sensibili al calendario macro.",
                fails_when="Mercati poco sensibili al dato o quando il consenso è poco affidabile.",
                strategy_use="News filter, bias direzionale, post-event setup.",
                common_mistakes=[
                    "Bloccare tutto il trading anche quando il dato è irrilevante per il bot.",
                    "Non modellare pre e post-event windows.",
                ],
                example="Blocca breakout EURUSD nei 20 minuti prima del CPI e riattivali solo dopo conferma del regime post-evento.",
            ),
            indicator(
                "funding-open-interest",
                "Funding / Open Interest",
                formula="Costo del posizionamento + variazione OI",
                interpretation="Aiuta a leggere crowding e squeeze risk, soprattutto su crypto.",
                works_when="Mercati perpetual futures o derivati con OI trasparente.",
                fails_when="Asset senza dato affidabile o timeframe troppo lenti.",
                strategy_use="Filtro di crowding, avoidance di carry crowded, risk overlay.",
                common_mistakes=[
                    "Usarlo senza contesto di prezzo e volume.",
                    "Scambiare crowding per timing perfetto.",
                ],
                example="Se funding e OI crescono troppo insieme al prezzo, riduci la fiducia in continuation long tardive.",
            ),
        ],
    },
]


ACADEMY_MODULES = [
    {
        "id": "algo-foundations",
        "title": "Fondamenti di Trading Algoritmico",
        "category": "Core",
        "difficulty": "Base",
        "estimated_hours": 3.5,
        "description": "Le basi operative per passare da idea discrezionale a sistema codificabile, misurabile e ripetibile.",
        "objectives": [
            "Distinguere idea, ipotesi e regola codificabile.",
            "Capire il ciclo ricerca → validazione → deploy.",
            "Separare edge reale da storytelling di mercato.",
        ],
        "lessons": [
            lesson(
                "algo-foundations-hypothesis",
                "Da intuizione a ipotesi testabile",
                duration_min=28,
                difficulty="Base",
                summary="La differenza tra una buona intuizione di mercato e una regola che un motore può davvero eseguire.",
                theory="Un sistema algoritmico nasce da un'ipotesi falsificabile: in quali condizioni il mercato tende a fare qualcosa, con quale frequenza, e in quali condizioni smette di farlo. L'utente deve imparare a scrivere una regola che abbia trigger, invalidazione, rischio e contesto. Questa è la base dell'intera app: Visari non trasforma frasi vaghe in magia, ma struttura ipotesi testabili.",
                why_it_matters="Questa lezione è il punto in cui smetti di descrivere il mercato come lo percepisci e inizi a descriverlo come lo deve leggere una macchina. Se non superi questo passaggio, builder, backtest e bot finale diventano solo un involucro tecnico attorno a una logica ancora vaga.",
                framework=[
                    "Parti da un evento osservabile, non da un giudizio: breakout, pullback, cross, squeeze, ritorno alla media.",
                    "Definisci la condizione di invalidazione prima ancora dell'entry: quando il setup smette di avere senso?",
                    "Aggiungi il contesto che rende l'evento selettivo: trend, volatilità, orario, sessione, news.",
                    "Traduci tutto in una frase che un bot possa eseguire senza interpretare nulla.",
                ],
                practical=[
                    "Scrivi il trigger come evento osservabile: breakout, pullback, cross, ritorno alla media.",
                    "Definisci sempre dove il setup non vale più.",
                    "Aggiungi un contesto: trend, volatilità, orario, news.",
                ],
                mistakes=[
                    "Confondere 'mi sembra forte' con una condizione misurabile.",
                    "Non definire quando NON entrare.",
                    "Pensare che la codifica da sola crei edge.",
                ],
                case_study="Una strategia 'compra quando il mercato è forte' diventa: compra EURUSD se chiude sopra il massimo delle ultime 20 barre con EMA20 > EMA50, ATR in aumento e fuori dalla finestra CPI.",
                app_exercise=[
                    "Apri il Builder e descrivi una tua idea in una sola frase grezza.",
                    "Riformulala in tre blocchi: trigger, invalidazione, contesto.",
                    "Controlla se ogni blocco contiene parole misurabili o solo impressioni soggettive.",
                ],
                checklist=[
                    "Il trigger usa parole osservabili e non psicologiche.",
                    "Esiste una condizione esplicita in cui il setup non è più valido.",
                    "Il rischio non è lasciato implicito.",
                    "Il contesto dice quando il segnale va ignorato.",
                ],
                before_continue=[
                    "Se una persona diversa da te non saprebbe eseguire la regola nello stesso modo, la regola non è ancora pronta.",
                    "Se la tua frase richiede interpretazione discrezionale, il bot non potrà implementarla in modo robusto.",
                ],
                app_links=[APP_CTA_BUILDER, APP_CTA_WORKSPACE],
            ),
            lesson(
                "algo-foundations-research-loop",
                "Il loop professionale di ricerca",
                duration_min=24,
                difficulty="Base",
                summary="Come lavora davvero un team quant: idea, formalizzazione, test, review, iterazione.",
                theory="Il processo corretto non è lineare ma iterativo. Si parte da un'idea, la si formalizza, si testa, si misurano gli errori, si corregge, si ri-testa e solo dopo si valuta il deploy. La piattaforma è costruita proprio per supportare questo loop con Builder, Bot Lab e Desk.",
                why_it_matters="Molti trader saltano direttamente dall'idea al bot. Il problema è che così non sanno mai quale parte ha creato o distrutto il risultato. Il loop professionale serve proprio a isolare ogni passaggio: ipotesi, struttura, validazione, revisione e supervisione live.",
                framework=[
                    "Idea: formula l'ipotesi di edge e il contesto di mercato che la giustifica.",
                    "Formalizzazione: costruisci regole chiare, parametri e filtri nel Builder.",
                    "Validazione: controlla se il comportamento regge fuori campione e sotto stress.",
                    "Revisione: correggi solo una componente alla volta.",
                    "Governance: una volta pronto, il bot va sorvegliato nel Desk e non abbandonato.",
                ],
                practical=[
                    "Usa il Builder per trasformare l'idea in specifica.",
                    "Usa il Backtest per capire se il comportamento regge fuori campione.",
                    "Usa il Desk per monitorare drift e governance dopo la validazione.",
                ],
                mistakes=[
                    "Saltare direttamente dall'idea al bot live.",
                    "Cambiare troppe variabili insieme tra un test e l'altro.",
                    "Scambiare un singolo backtest positivo per robustezza.",
                ],
                app_exercise=[
                    "Prendi un'idea già scritta e decidi in quale fase del loop si trova davvero oggi.",
                    "Se è solo un'intuizione, non passare al backtest: prima formalizzala.",
                    "Se hai già un bot, aprilo in Bot Lab e identifica un solo difetto da correggere.",
                ],
                checklist=[
                    "Sai dire qual è la singola ipotesi che stai testando.",
                    "Sai cosa stai modificando tra una versione e l'altra.",
                    "Sai quali risultati stai usando per promuovere o scartare il bot.",
                ],
                before_continue=[
                    "Un bot professionale non nasce da un colpo di fortuna ma da un ciclo disciplinato di miglioramento.",
                ],
                app_links=[APP_CTA_BUILDER, APP_CTA_DESK],
            ),
            lesson(
                "algo-foundations-style-taxonomy",
                "Trend, mean reversion, breakout, carry: famiglie di edge",
                duration_min=30,
                difficulty="Base",
                summary="Le grandi famiglie di strategie e il regime di mercato in cui tendono a funzionare.",
                theory="Ogni strategia compra o vende una struttura di mercato. Trend-following compra persistenza. Mean reversion compra ritorno alla media. Breakout compra espansione. Carry compra tempo e differenziale. Capire la famiglia giusta evita di mischiare logiche incompatibili nello stesso bot.",
                why_it_matters="Quasi tutti i bot mediocri diventano confusi perché mescolano famiglie di edge diverse nello stesso sistema. Se non sai in quale famiglia vive la tua idea, non saprai neanche in quale regime proteggerla o spegnerla.",
                framework=[
                    "Trend-following: cerca persistenza, continuità e follow-through.",
                    "Mean reversion: cerca eccesso e ritorno al fair value locale.",
                    "Breakout: compra espansione e cambiamento di struttura.",
                    "Carry: monetizza tempo, differenziale o premio di rischio, non solo movimento.",
                ],
                practical=[
                    "Classifica sempre la tua idea in una famiglia principale.",
                    "Associa a ogni famiglia il regime in cui tende a performare.",
                    "Costruisci filtri per evitare i regimi sbagliati.",
                ],
                mistakes=[
                    "Mescolare trigger trend con exit mean reversion senza una ragione testata.",
                    "Usare lo stesso risk model su strategie con edge diversi.",
                ],
                app_exercise=[
                    "Apri una tua strategia e scrivi in una riga quale edge sta cercando di comprare.",
                    "Nel Desk, osserva se il regime corrente è coerente con quella famiglia.",
                ],
                checklist=[
                    "Hai identificato una famiglia dominante di edge.",
                    "Hai definito il regime giusto e quello sbagliato per quella famiglia.",
                    "Il risk model è coerente con il tipo di edge.",
                ],
                app_links=[APP_CTA_BUILDER, APP_CTA_DESK],
            ),
        ],
    },
    {
        "id": "market-foundations",
        "title": "Fondamenti di Mercati Finanziari",
        "category": "Mercati",
        "difficulty": "Base",
        "estimated_hours": 2.8,
        "description": "Solo la parte di teoria di mercato che serve davvero per costruire sistemi quantitativi sensati.",
        "objectives": [
            "Capire sessioni, liquidità, rollover e caratteristiche degli strumenti.",
            "Leggere il mercato come ambiente operativo, non come teoria astratta.",
            "Collegare struttura di mercato e qualità del backtest.",
        ],
        "lessons": [
            lesson(
                "market-foundations-sessions",
                "Sessioni, liquidità e finestre operative",
                duration_min=22,
                difficulty="Base",
                summary="Perché il comportamento di un bot cambia tra Asia, London e New York.",
                theory="Un segnale che funziona nella sessione di Londra può degradare completamente in Asia. Spread, range, velocità e probabilità di follow-through sono session-dependent. Le strategie professionali definiscono sempre una finestra operativa coerente con il loro edge.",
                practical=[
                    "Traccia la sessione nel Builder.",
                    "Evita orari a liquidità debole se il sistema dipende da breakout.",
                    "Misura spread e slippage per sessione.",
                ],
                mistakes=["Usare 24/5 come default senza validazione.", "Ignorare rollover e orari news."],
                app_links=[APP_CTA_BUILDER],
            ),
            lesson(
                "market-foundations-contract-specs",
                "Specifiche strumento e impatto sul bot",
                duration_min=18,
                difficulty="Base",
                summary="Tick size, pip value, commissioni e vincoli del broker entrano nel rischio reale del sistema.",
                theory="Due strategie identiche possono produrre risultati completamente diversi se cambiano tick size, valore del contratto, spread e leva effettiva. Un bot profittevole in teoria può diventare mediocre solo per costi e execution.",
                practical=[
                    "Normalizza il sizing in funzione del contratto.",
                    "Controlla commissioni e spread medi per strumento.",
                    "Adatta stop e TP al tick size reale.",
                ],
                mistakes=["Testare con costi nulli.", "Applicare parametri Forex a indici o metalli."],
                app_links=[APP_CTA_BUILDER, APP_CTA_DESK],
            ),
            lesson(
                "market-foundations-regimes",
                "Regimi di mercato che contano davvero",
                duration_min=26,
                difficulty="Intermedio",
                summary="Trend, range, compressione, espansione e transizione: la tassonomia utile per i bot.",
                theory="I bot non falliscono solo perché l'edge era debole: spesso falliscono perché il regime per cui erano progettati è cambiato. La lettura del regime deve diventare parte del design, non un commento posteriore.",
                practical=[
                    "Crea un filtro di regime semplice ma misurabile.",
                    "Usa volatilità e struttura del prezzo come contesto.",
                    "Separa performance per regime nel Desk.",
                ],
                mistakes=["Definire il regime in modo retrospettivo.", "Usare troppe categorie inutili."],
                app_links=[APP_CTA_DESK, APP_CTA_BUILDER],
            ),
        ],
    },
    {
        "id": "stats-probability",
        "title": "Statistica e Probabilità per il Trading",
        "category": "Quant",
        "difficulty": "Intermedio",
        "estimated_hours": 4.2,
        "description": "La statistica minima ma seria per capire se un edge è reale, fragile o solo rumore campionario.",
        "objectives": [
            "Leggere distribuzioni, aspettativa e incertezza.",
            "Capire campione, confidenza e significatività pratica.",
            "Evitare di scambiare rumore per edge.",
        ],
        "lessons": [
            lesson(
                "stats-distribution-expectancy",
                "Distribuzione dei trade ed expectancy",
                duration_min=32,
                difficulty="Intermedio",
                summary="Perché il profit factor non basta e perché la forma della distribuzione conta quanto la media.",
                theory="Un sistema può avere expectancy positiva ma dipendere da pochi outlier, oppure avere hit rate alto ma payoff troppo basso. La distribuzione dei trade ti dice dove vive davvero l'edge: nella frequenza, nell'asimmetria, nei fat tail o nella stabilità dei risultati.",
                practical=[
                    "Guarda hit rate, payoff, expectancy e skew insieme.",
                    "Controlla se pochi trade spiegano gran parte del profitto.",
                    "Usa istogrammi e percentili, non solo medie.",
                ],
                mistakes=[
                    "Fissarsi sul win rate.",
                    "Non isolare gli outlier che tengono in piedi il sistema.",
                    "Ignorare la dispersione dei risultati.",
                ],
                case_study="Un bot con 68% win rate ma payoff 0.55R può essere peggiore di uno con 42% win rate e payoff 2.1R.",
                app_links=[APP_CTA_DESK, APP_CTA_BUILDER],
            ),
            lesson(
                "stats-sample-confidence",
                "Campione, confidenza e robustezza minima",
                duration_min=28,
                difficulty="Intermedio",
                summary="Quanti trade bastano davvero per fidarsi di un risultato e come leggere l'incertezza.",
                theory="Non esiste un numero magico di trade valido per tutti, ma esiste un principio forte: più l'edge è sottile, più dati servono. Devi imparare a leggere l'ampiezza dell'incertezza, non solo il valore centrale. Un backtest con 18 trade e Sharpe alto non è automaticamente forte: può essere solo rumoroso.",
                practical=[
                    "Misura la sensibilità dei risultati al campione.",
                    "Confronta segmenti temporali diversi.",
                    "Usa walk-forward e Monte Carlo come estensione della logica statistica.",
                ],
                mistakes=[
                    "Dichiarare robusto un sistema con sample ridicolo.",
                    "Ignorare i cluster temporali dei trade.",
                    "Confondere significatività statistica con utilità economica.",
                ],
                app_links=[APP_CTA_DESK, APP_CTA_WORKSPACE],
            ),
            lesson(
                "stats-hypothesis-testing",
                "Test d’ipotesi e realtà operativa",
                duration_min=30,
                difficulty="Intermedio",
                summary="Come usare il pensiero statistico senza cadere nella trappola del p-value fine a sé stesso.",
                theory="Nel trading conta più la robustezza economica che la purezza accademica del test. I test aiutano a scartare idee deboli, ma non sostituiscono stabilità, regime consistency e capacità di sostenere costi reali. Devi usarli come filtro, non come timbro magico.",
                practical=[
                    "Usa i test per rifiutare idee fragili, non per venderti certezze.",
                    "Combina sempre test statistici e analisi di regime.",
                    "Valuta se il risultato sopravvive ai costi e alla frequenza reale.",
                ],
                mistakes=[
                    "Fare data mining finché esce un p-value carino.",
                    "Non correggere per multipli tentativi.",
                ],
                app_links=[APP_CTA_DESK],
            ),
        ],
    },
    {
        "id": "data-features",
        "title": "Data Analysis e Feature Engineering",
        "category": "Quant",
        "difficulty": "Intermedio",
        "estimated_hours": 3.4,
        "description": "Come trasformare OHLC, volume e contesto in feature pulite, utili e non tossiche.",
        "objectives": [
            "Pulire dati e capire cosa si può usare davvero.",
            "Costruire feature con interpretazione economica.",
            "Evitare leakage e feature troppo deboli.",
        ],
        "lessons": [
            lesson(
                "data-features-ohlc",
                "Pulizia OHLC e qualità del dataset",
                duration_min=20,
                difficulty="Intermedio",
                summary="Il miglior modello del mondo fallisce su dati sporchi o incoerenti.",
                theory="Prima di parlare di edge, bisogna sapere cosa stai testando. Mancanze, fusi orari, split, dati demo e compressioni errate cambiano i risultati. La qualità del dato è parte della strategia.",
                practical=["Controlla buchi, timezone e valori anomali.", "Normalizza sessioni e frequenze."],
                mistakes=["Usare feed demo come se fossero production-grade.", "Mischiare fonti incompatibili."],
                app_links=[APP_CTA_BUILDER, APP_CTA_DESK],
            ),
            lesson(
                "data-features-transformations",
                "Feature trasformative con senso economico",
                duration_min=24,
                difficulty="Intermedio",
                summary="Una feature utile è spiegabile, stabile e coerente col meccanismo dell'edge.",
                theory="Buone feature non sono solo manipolazioni matematiche: devono avere una ragione. Range normalizzati, ritorni, slope, z-score, session range e momentum percentile sono esempi forti perché raccontano qualcosa di reale sul mercato.",
                practical=["Prefers feature robuste e leggibili.", "Normalizza per volatilità quando possibile."],
                mistakes=["Aggiungere decine di feature ridondanti.", "Usare feature senza spiegazione economica."],
                app_links=[APP_CTA_BUILDER],
            ),
            lesson(
                "data-features-labels",
                "Feature, target e leakage",
                duration_min=18,
                difficulty="Intermedio",
                summary="Ogni trasformazione deve rispettare la freccia del tempo.",
                theory="Se una feature usa anche indirettamente informazione futura, il sistema sembra geniale in backtest e poi si rompe. Il leakage è spesso invisibile: rolling windows mal definite, aggregati globali, normalizzazioni future-aware.",
                practical=["Usa solo dati disponibili al timestamp decisionale.", "Controlla tutte le rolling window."],
                mistakes=["Normalizzare con statistiche dell'intero campione.", "Usare target o label per costruire feature."],
                app_links=[APP_CTA_DESK],
            ),
        ],
    },
    {
        "id": "strategy-core",
        "title": "Strategia (Core)",
        "category": "Core",
        "difficulty": "Intermedio",
        "estimated_hours": 5.4,
        "description": "Il cuore della piattaforma: dalla logica di Ernest Chan alle estensioni moderne su regime, robustezza e iterazione.",
        "objectives": [
            "Progettare una strategia come ipotesi strutturata.",
            "Separare edge, filtro e execution layer.",
            "Costruire bot migliorabili nel tempo.",
        ],
        "lessons": [
            lesson(
                "strategy-core-design-stack",
                "Design stack: trigger, filtro, rischio, governance",
                duration_min=34,
                difficulty="Intermedio",
                summary="Una strategia forte non è un solo segnale: è un insieme di livelli che lavorano insieme.",
                theory="Il segnale di entry è solo una parte. Un sistema professionale ha almeno quattro layer: trigger, filtro di contesto, risk model e governance. Questa distinzione è centrale anche in Visari: Builder per formalizzare, Backtest per validare, Desk per governare runtime e drift.",
                practical=[
                    "Scrivi il trigger separato dal filtro di contesto.",
                    "Tratta il risk layer come parte del design, non come accessorio.",
                    "Definisci cosa fa scattare una pausa operativa.",
                ],
                mistakes=[
                    "Pensare che migliorare il trigger basti a salvare un sistema mediocre.",
                    "Mettere il risk management fuori dal design della strategia.",
                ],
                case_study="Un breakout intraday con vol filter, session filter, daily loss guard e kill-switch ha spesso più edge reale del breakout 'puro'.",
                app_links=[APP_CTA_BUILDER, APP_CTA_DESK],
            ),
            lesson(
                "strategy-core-chan-principles",
                "Ernest Chan: cosa tenere e cosa estendere",
                duration_min=30,
                difficulty="Intermedio",
                summary="I principi classici di Chan restano solidi: mean reversion, pairs, cross-sectional, ma vanno integrati con regime e deployment discipline.",
                theory="Chan insegna a ragionare per edge misurabile, sample, costi e adattamento. Oggi però bisogna estendere quel framework con regime detection, drift monitoring, governance live e validazione più robusta. L'Academy usa Chan come base, non come punto di arrivo.",
                practical=[
                    "Prendi da Chan l'ossessione per la testabilità.",
                    "Aggiungi sempre regime e deployment protocol.",
                    "Valuta la strategia come processo, non solo come risultato.",
                ],
                mistakes=[
                    "Copiare una famiglia di strategie senza capire in quale regime vive.",
                    "Restare solo su backtest statico e ignorare il dopo.",
                ],
                app_links=[APP_CTA_BUILDER, APP_CTA_DESK],
            ),
            lesson(
                "strategy-core-regime-aware",
                "Strategie regime-aware",
                duration_min=36,
                difficulty="Avanzato",
                summary="Un bot professionale sa quando il proprio edge è attivo e quando deve ridurre intensità o spegnersi.",
                theory="La maggior parte dei sistemi degrada perché continua a operare anche quando il regime non è più coerente. Un modello regime-aware usa volatilità, struttura prezzo, sessione o contesto macro per attivare, modulare o disattivare il segnale.",
                practical=[
                    "Definisci 2 o 3 regimi operativi massimi.",
                    "Associa a ogni regime un set di segnali o un livello di rischio.",
                    "Monitora il drift regime nel Desk.",
                ],
                mistakes=[
                    "Creare tassonomie di regime troppo complesse.",
                    "Stimare il regime in modo retrospettivo anziché operativo.",
                ],
                app_links=[APP_CTA_DESK, APP_CTA_BUILDER],
            ),
            lesson(
                "strategy-core-improvement-loop",
                "Come migliorare un bot senza distruggerlo",
                duration_min=26,
                difficulty="Avanzato",
                summary="Le revisioni utili cambiano una sola ipotesi per volta e misurano l'impatto in modo disciplinato.",
                theory="Migliorare un bot non significa aggiungere indicatori a caso. Significa formulare un problema preciso — troppo rumore, drawdown eccessivo, operatività in news, sizing incoerente — e intervenire con una modifica tracciabile. Il Bot Lab è progettato proprio per questo.",
                practical=[
                    "Definisci un difetto osservabile prima di modificare il codice.",
                    "Cambia una sola componente alla volta.",
                    "Confronta prima/dopo su stabilità, drawdown e qualità del segnale.",
                ],
                mistakes=[
                    "Fare revisioni omnibus.",
                    "Confondere complessità extra con miglioramento reale.",
                ],
                app_links=[APP_CTA_WORKSPACE, APP_CTA_DESK],
            ),
        ],
    },
    {
        "id": "indicator-library",
        "title": "Signal & Indicator Library",
        "category": "Library",
        "difficulty": "Misto",
        "estimated_hours": 6.0,
        "description": "Enciclopedia pratica dei segnali usati nel trading quantitativo, con focus su quando funzionano davvero e quando no.",
        "objectives": [
            "Capire il senso economico dei segnali, non solo la formula.",
            "Scegliere indicatori coerenti con il regime.",
            "Integrare i segnali in strategie testabili nella piattaforma.",
        ],
        "lessons": [
            lesson(
                "indicator-library-map",
                "Come usare la libreria segnali",
                duration_min=18,
                difficulty="Base",
                summary="Una mappa per leggere gli indicatori come strumenti di design, non come collezione casuale.",
                theory="Gli indicatori non sono edge. Sono compressioni informative del prezzo, del volume o del contesto. La domanda giusta non è 'quale indicatore è migliore?', ma 'quale indicatore misura il fenomeno che voglio tradare?'.",
                practical=["Parti dal fenomeno di mercato e poi scegli il segnale.", "Usa massimo 1 trigger + 1 filtro + 1 risk overlay."],
                mistakes=["Impilare cinque oscillatori simili.", "Usare indicatori ridondanti come falsa conferma."],
                app_links=[APP_CTA_BUILDER],
            ),
            lesson(
                "indicator-library-regime-selection",
                "Scelta del segnale per regime",
                duration_min=20,
                difficulty="Intermedio",
                summary="Trend, range e compressione richiedono strumenti diversi.",
                theory="Un EMA crossover in range è rumore. Un RSI in trend forte è spesso solo controtrend prematuro. La selezione del segnale deve partire dal regime e dall'orizzonte operativo.",
                practical=["Usa il Desk per leggere il regime corrente.", "Scegli segnali che misurano lo stesso fenomeno che vuoi sfruttare."],
                mistakes=["Cercare indicatori universali.", "Non cambiare filtri quando cambia il regime."],
                app_links=[APP_CTA_DESK, APP_CTA_BUILDER],
            ),
        ],
        "indicator_categories": INDICATOR_LIBRARY,
    },
    {
        "id": "backtesting",
        "title": "Backtesting professionale",
        "category": "Validation",
        "difficulty": "Intermedio",
        "estimated_hours": 4.8,
        "description": "Costruire backtest credibili, non scenari ottimistici vestiti da ricerca.",
        "objectives": [
            "Capire cosa rende un backtest credibile.",
            "Misurare robustezza, non solo performance.",
            "Leggere i risultati in funzione del deploy reale.",
        ],
        "lessons": [
            lesson(
                "backtesting-simulator",
                "Come ragiona un simulatore serio",
                duration_min=34,
                difficulty="Intermedio",
                summary="Ordine temporale, costi, split, fill assumptions e stato della posizione cambiano tutto.",
                theory="Un motore serio non guarda il futuro, applica costi plausibili, separa in-sample e out-of-sample e mantiene lo stato delle posizioni nel tempo. Qualsiasi scorciatoia qui crea risultati troppo belli per essere veri.",
                practical=[
                    "Verifica sempre costi, orizzonte temporale e qualità dati.",
                    "Guarda se il motore sta usando dati storici reali o sintetici.",
                    "Interpreta il report in ottica di deploy, non di narrativa.",
                ],
                mistakes=[
                    "Backtest su dati demo o poco profondi come se fossero produzione.",
                    "Costi nulli, fill perfetti e sizing irrealistico.",
                ],
                app_links=[APP_CTA_BUILDER, APP_CTA_DESK],
            ),
            lesson(
                "backtesting-walk-forward",
                "Walk-forward e rolling validation",
                duration_min=28,
                difficulty="Avanzato",
                summary="Il test più importante non è il fit sul passato ma la tenuta su periodi mai visti durante il design.",
                theory="La walk-forward analysis è la disciplina base per capire se il sistema regge quando le condizioni cambiano. Non serve solo a validare: serve a capire quando una strategia richiede re-calibrazione o quando è troppo sensibile per vivere in produzione.",
                practical=[
                    "Usa finestre train/test realistiche.",
                    "Guarda stabilità dei parametri, non solo performance media.",
                    "Misura la dispersione tra segmenti temporali.",
                ],
                mistakes=["Training troppo lungo e test ridicolo.", "Cambiare parametri ogni volta senza criterio operativo."],
                app_links=[APP_CTA_DESK],
            ),
            lesson(
                "backtesting-monte-carlo",
                "Monte Carlo, distribuzione degli esiti e realtà psicologica",
                duration_min=26,
                difficulty="Avanzato",
                summary="Un sistema può essere valido e comunque vivere sequenze di drawdown peggiori del backtest lineare.",
                theory="Monte Carlo e stress distribution servono a capire la gamma di risultati possibili, non il risultato più bello. Sono essenziali per stimare drawdown plausibili, dipendenza dalla sequenza dei trade e tenuta psicologica/operativa.",
                practical=["Valuta percentile 5/50/95 su capitale e drawdown.", "Tratta il worst-case come design input per il risk layer."],
                mistakes=["Usare solo la curva equity lineare.", "Ignorare la fragilità alla sequenza dei trade."],
                app_links=[APP_CTA_DESK],
            ),
        ],
    },
    {
        "id": "bias-errors",
        "title": "Bias e errori",
        "category": "Validation",
        "difficulty": "Intermedio",
        "estimated_hours": 3.2,
        "description": "Tutti i modi in cui un sistema può sembrare brillante solo perché il processo è sbagliato.",
        "objectives": [
            "Riconoscere i bias che gonfiano i risultati.",
            "Capire come prevenirli in design, feature e test.",
            "Collegare ogni bias a un controllo operativo.",
        ],
        "lessons": [
            lesson(
                "bias-lookahead",
                "Lookahead bias",
                duration_min=20,
                difficulty="Intermedio",
                summary="Il bias più devastante: vedere il futuro anche solo di poco.",
                theory="Basta una feature costruita male o un trigger che usa il massimo della barra prima della sua chiusura per gonfiare artificialmente i risultati. Il lookahead spesso è sottile, non sempre evidente.",
                practical=["Controlla ogni rolling window.", "Usa solo dati disponibili al timestamp decisionale."],
                mistakes=["Usare il close finale della barra per entrare all'interno della stessa barra."],
                app_links=[APP_CTA_BUILDER],
            ),
            lesson(
                "bias-overfitting",
                "Overfitting",
                duration_min=24,
                difficulty="Intermedio",
                summary="Quando la strategia impara il rumore del passato invece della struttura del mercato.",
                theory="Ogni grado di libertà aggiuntivo aumenta la capacità di adattarsi al passato. La domanda non è 'quanti parametri ho?', ma 'quanta complessità sto usando rispetto alla quantità e qualità del campione?'.",
                practical=["Misura stabilità parametrica.", "Preferisci logiche parsimoniose."],
                mistakes=["Grid search enorme su campione piccolo.", "Aggiungere filtri solo perché migliorano il backtest."],
                app_links=[APP_CTA_DESK],
            ),
            lesson(
                "bias-survivorship",
                "Survivorship, selection e leakage operativo",
                duration_min=18,
                difficulty="Intermedio",
                summary="Anche la scelta del dataset o del campione può falsare l'edge.",
                theory="Se testi solo asset sopravvissuti, o solo periodi belli, o usi un dataset già ripulito con informazione futura implicita, il risultato è distorto. Il bias non vive solo nel codice: vive nelle scelte di ricerca.",
                practical=["Documenta sempre da dove arrivano i dati.", "Confronta periodi diversi e condizioni diverse."],
                mistakes=["Selezionare strategie solo dopo aver visto il risultato.", "Scartare manualmente i casi brutti."],
                app_links=[APP_CTA_WORKSPACE],
            ),
        ],
    },
    {
        "id": "risk-management",
        "title": "Risk Management avanzato",
        "category": "Core",
        "difficulty": "Avanzato",
        "estimated_hours": 4.0,
        "description": "Il livello che decide se un bot sopravvive abbastanza a lungo da far emergere il proprio edge.",
        "objectives": [
            "Costruire sizing coerente con il rischio reale.",
            "Progettare guardie, stop e limiti giornalieri.",
            "Gestire il rischio come sistema, non come numeretto.",
        ],
        "lessons": [
            lesson(
                "risk-sizing",
                "Position sizing che non ti distrugge",
                duration_min=24,
                difficulty="Avanzato",
                summary="Sizing, leva e frequenza devono convivere con la distribuzione degli esiti del bot.",
                theory="Il sizing non è un add-on. Determina drawdown, probabilità di rovina e sostenibilità psicologica. Un edge mediocre con sizing sensato sopravvive più di un edge buono con sizing suicida.",
                practical=["Dimensiona per rischio monetario, non per convinzione.", "Ricalcola sizing su volatilità e stop reali."],
                mistakes=["Size fisse indipendenti dal regime.", "Leva aggressiva su sistemi fragili."],
                app_links=[APP_CTA_BUILDER, APP_CTA_DESK],
            ),
            lesson(
                "risk-drawdown-controls",
                "Drawdown guard, loss guard, kill switch",
                duration_min=22,
                difficulty="Avanzato",
                summary="I bot professionali hanno freni operativi espliciti.",
                theory="Daily loss guard, drawdown cap, stop on anomaly e pause after regime shift non riducono solo il rischio: proteggono la ricerca dal continuare a operare fuori profilo.",
                practical=["Definisci soglie a livello trade/day/bot.", "Configura il Desk per monitorarle."],
                mistakes=["Soglie arbitrarie non legate alla distribuzione del sistema."],
                app_links=[APP_CTA_DESK],
            ),
            lesson(
                "risk-risk-of-ruin",
                "Risk of ruin e sopravvivenza",
                duration_min=20,
                difficulty="Avanzato",
                summary="La prima missione di un bot è restare vivo abbastanza a lungo.",
                theory="Un sistema con edge teorico può comunque fallire per sequenze avverse se il risk budget è sbagliato. La probabilità di rovina è un concetto operativo, non solo matematico.",
                practical=["Collega sizing, drawdown e frequenza trade.", "Valuta scenari pessimi, non solo medi."],
                mistakes=["Sottostimare cluster di perdite.", "Usare rischio per trade alto su sistemi ad alta frequenza."],
                app_links=[APP_CTA_DESK],
            ),
        ],
    },
    {
        "id": "execution-microstructure",
        "title": "Execution & microstruttura",
        "category": "Execution",
        "difficulty": "Avanzato",
        "estimated_hours": 3.3,
        "description": "Dove molti bot 'profittevoli' perdono il loro edge: costi, slippage, timing e qualità del fill.",
        "objectives": [
            "Capire il costo reale dell'esecuzione.",
            "Distinguere segnali belli da segnali eseguibili.",
            "Introdurre disciplina execution-aware nel design.",
        ],
        "lessons": [
            lesson(
                "execution-spread-slippage",
                "Spread, slippage e deterioramento dell'edge",
                duration_min=22,
                difficulty="Avanzato",
                summary="Il confine tra bot buono e bot inutile spesso è un paio di tick di esecuzione.",
                theory="Il backtest deve rappresentare quanto possibile i costi di esecuzione. Strategie a margine sottile, altissima frequenza o breakout tardivi sono le prime a morire quando entrano spread e slippage reali.",
                practical=["Stressa i costi nei test.", "Evita setup sensibili a fill perfetti."],
                mistakes=["Costi costanti irrealistici.", "Nessun filtro spread nei bot live."],
                app_links=[APP_CTA_BUILDER, APP_CTA_DESK],
            ),
            lesson(
                "execution-timing",
                "Timing di ordine e qualità del trigger",
                duration_min=18,
                difficulty="Avanzato",
                summary="Non tutti i trigger sono eseguibili allo stesso modo.",
                theory="Una rottura di massimo vista su OHLC può essere difficile da catturare bene in live. Il timing dell'ordine, il tipo di ordine e la velocità del mercato contano quanto il segnale.",
                practical=["Confronta close-based, stop order e pullback entry.", "Scegli trigger coerenti con la microstruttura."],
                mistakes=["Progettare trigger che richiedono fill perfetti."],
                app_links=[APP_CTA_BUILDER],
            ),
            lesson(
                "execution-liquidity",
                "Liquidità e qualità del mercato",
                duration_min=18,
                difficulty="Intermedio",
                summary="Ogni strategia vive dentro un mercato con frizioni, non dentro una curva pulita.",
                theory="Liquidità, profondità e regime orario cambiano l'effettiva trasportabilità del backtest in runtime. Questo vale anche per asset molto popolari.",
                practical=["Evita orari e strumenti fuori capacità di esecuzione del bot.", "Riduci size se la profondità non sostiene la strategia."],
                mistakes=["Applicare size teoriche a mercati sottili."],
                app_links=[APP_CTA_DESK],
            ),
        ],
    },
    {
        "id": "portfolio-construction",
        "title": "Portfolio construction",
        "category": "Portfolio",
        "difficulty": "Avanzato",
        "estimated_hours": 3.1,
        "description": "Come far convivere più bot senza moltiplicare rischio e ridondanza.",
        "objectives": [
            "Leggere correlazioni e overlap di rischio.",
            "Allocare capitale per edge, drawdown e stabilità.",
            "Pensare in termini di portafoglio, non di singolo bot.",
        ],
        "lessons": [
            lesson(
                "portfolio-correlation",
                "Correlazione utile vs ridondanza",
                duration_min=20,
                difficulty="Avanzato",
                summary="Due bot diversi nel codice possono essere quasi identici nel rischio.",
                theory="Se due sistemi comprano lo stesso regime, con gli stessi strumenti e lo stesso tipo di rischio, il portafoglio non è diversificato. Serve distinguere varietà superficiale da diversificazione vera.",
                practical=["Confronta PnL, drawdown e regime exposure tra bot.", "Evita di sommare bot fratelli."],
                mistakes=["Contare strategie invece di contare esposizioni reali."],
                app_links=[APP_CTA_DESK],
            ),
            lesson(
                "portfolio-allocation",
                "Allocazione del capitale",
                duration_min=18,
                difficulty="Avanzato",
                summary="Il capitale va dato ai sistemi con miglior profilo rischio/stabilità, non solo a quelli con ritorno più alto.",
                theory="L'allocazione deve tenere conto di drawdown, stabilità, regime sensitivity e correlazione. Il miglior bot non è sempre quello che deve ricevere più capitale.",
                practical=["Bilancia edge, drawdown e robustezza.", "Rialloca quando il regime cambia."],
                mistakes=["Allocare solo sul ranking di rendimento."],
                app_links=[APP_CTA_DESK],
            ),
            lesson(
                "portfolio-rebalance",
                "Review e rebalance",
                duration_min=16,
                difficulty="Intermedio",
                summary="Un portafoglio di bot va rivisto come un desk, non lasciato fermo per mesi.",
                theory="Regimi, correlazioni e drift cambiano. Il rebalance periodico è parte della governance del portafoglio algoritmico.",
                practical=["Definisci una cadenza di review.", "Usa il Desk come control room portfolio-aware."],
                mistakes=["Reagire a ogni giornata negativa.", "Non avere una cadenza fissa di review."],
                app_links=[APP_CTA_DESK],
            ),
        ],
    },
    {
        "id": "python-essentials",
        "title": "Python Essentials for Trading Bots",
        "category": "Implementation",
        "difficulty": "Base → Intermedio",
        "estimated_hours": 4.6,
        "description": "Solo il Python che serve davvero per costruire, leggere e migliorare bot quantitativi dentro Visari.",
        "objectives": [
            "Capire le basi Python utili al trading sistematico.",
            "Usare pandas e numpy su dati OHLC.",
            "Collegare segnali, simulazione e motore della piattaforma.",
        ],
        "lessons": [
            lesson(
                "python-basics-trading",
                "Python minimo utile per trader quantitativi",
                duration_min=30,
                difficulty="Base",
                summary="Variabili, funzioni, condizioni e strutture dati: solo ciò che serve per leggere e scrivere logiche di trading.",
                theory="Un trader non ha bisogno di diventare software engineer per ragionare bene sui bot. Ha però bisogno di capire come una regola diventa codice: input, condizioni, funzioni, liste, dizionari e controllo del flusso. Questa lezione riduce l'attrito tra idea di strategia e logica implementata.",
                practical=[
                    "Scrivi condizioni if/else che imitano trigger di mercato.",
                    "Usa funzioni per separare segnale, filtro e rischio.",
                    "Ragiona sempre in termini di input → elaborazione → output.",
                ],
                mistakes=[
                    "Copiare codice senza capire quali dati usa.",
                    "Mescolare troppe responsabilità nella stessa funzione.",
                ],
                case_study="Una regola 'entra long se close > EMA20' diventa una funzione che restituisce LONG/None in modo leggibile e testabile.",
                app_links=[APP_CTA_BUILDER, APP_CTA_WORKSPACE],
            ),
            lesson(
                "python-pandas-ohlc",
                "pandas e OHLC senza inutili giri",
                duration_min=34,
                difficulty="Intermedio",
                summary="Caricare, pulire e trasformare serie OHLC in segnali misurabili.",
                theory="pandas è il coltellino svizzero del trading quantitativo: indicizzazione temporale, rolling window, trasformazioni vettoriali, join tra feature e target. L'obiettivo non è diventare data engineer, ma saper manipolare i dati in modo pulito e causale.",
                practical=[
                    "Crea ritorni, rolling mean, ATR proxy e z-score.",
                    "Usa shift e rolling in modo causale.",
                    "Controlla timezone e ordinamento indice prima di ogni test.",
                ],
                mistakes=[
                    "Normalizzare con il dataset intero.",
                    "Usare rolling window che guardano la barra corrente in modo scorretto.",
                ],
                app_links=[APP_CTA_BUILDER],
            ),
            lesson(
                "python-signals-simulation",
                "Dal segnale alla simulazione",
                duration_min=38,
                difficulty="Intermedio",
                summary="Come passare da una feature a un backtest leggibile e coerente con il motore dell’app.",
                theory="Un segnale utile non basta: devi sapere come si trasforma in entry, stop, take profit, size e stato della posizione. Questa lezione collega direttamente la logica Python con il motore di backtest e con il Builder di Visari.",
                practical=[
                    "Traduci un segnale in LONG/SHORT/flat.",
                    "Definisci stop e target come output espliciti.",
                    "Confronta la tua logica con il motore di backtest della piattaforma.",
                ],
                mistakes=[
                    "Calcolare il segnale su dati futuri.",
                    "Non mantenere lo stato della posizione in simulazione.",
                ],
                app_links=[APP_CTA_BUILDER, APP_CTA_DESK],
            ),
        ],
    },
    {
        "id": "live-deployment",
        "title": "Live trading & deployment",
        "category": "Execution",
        "difficulty": "Avanzato",
        "estimated_hours": 3.7,
        "description": "Dal bot validato al runtime disciplinato: setup, monitor, drift e incident response.",
        "objectives": [
            "Capire il protocollo corretto di messa in produzione.",
            "Monitorare il bot come sistema, non come promessa.",
            "Gestire drift, stop e revisione live.",
        ],
        "lessons": [
            lesson(
                "deployment-protocol",
                "Protocollo di pre-lancio",
                duration_min=24,
                difficulty="Avanzato",
                summary="Un bot non passa dal report al live in un click: serve un handoff operativo pulito.",
                theory="Checklist MT5, export, settaggi runtime, kill switch, finestra macro, broker fit e sizing iniziale sono parte del deploy. Un buon protocollo riduce errori operativi e false partenze.",
                practical=["Chiudi export, checklist e governance prima del live.", "Usa la guida finale dell’app come handoff."],
                mistakes=["Saltare la fase paper o il controllo parametri runtime."],
                app_links=[APP_CTA_WORKSPACE, APP_CTA_DESK],
            ),
            lesson(
                "deployment-live-monitoring",
                "Monitor live, drift e degenerazione",
                duration_min=26,
                difficulty="Avanzato",
                summary="Un bot profittevole non è uno che parte bene: è uno che viene monitorato quando il mercato cambia.",
                theory="Il runtime va confrontato col profilo validato. Se frequenza trade, drawdown, qualità esecuzione o regime si spostano fuori range, il bot sta degenerando anche se non è ancora in perdita grave.",
                practical=["Guarda drift, risk usage e cambi regime nel Desk.", "Definisci trigger di pausa e revisione."],
                mistakes=["Guardare solo il PnL giornaliero.", "Ignorare deviazioni perché il bot è ancora profittevole."],
                app_links=[APP_CTA_DESK],
            ),
            lesson(
                "deployment-incident-playbook",
                "Incident playbook",
                duration_min=18,
                difficulty="Avanzato",
                summary="Cosa fare quando il bot non si comporta come previsto.",
                theory="Errori runtime, mismatch segnali, degradazione macro, latenze, comportamento fuori profilo: tutto questo va gestito con una playbook semplice, rapida e ripetibile.",
                practical=["Decidi chi ferma il bot, quando e con quali segnali.", "Usa il Desk come control room, non come cruscotto passivo."],
                mistakes=["Avere solo una soglia di stop e nessun protocollo intermedio."],
                app_links=[APP_CTA_DESK],
            ),
        ],
    },
    {
        "id": "iteration",
        "title": "Iterazione e miglioramento continuo",
        "category": "Research",
        "difficulty": "Avanzato",
        "estimated_hours": 2.9,
        "description": "Come far evolvere i sistemi senza ricadere nel bricolage quantitativo.",
        "objectives": [
            "Impostare review disciplinate.",
            "Tracciare le modifiche con una tesi chiara.",
            "Usare Bot Lab e Desk come ciclo continuo di miglioramento.",
        ],
        "lessons": [
            lesson(
                "iteration-review",
                "Post-mortem e review periodica",
                duration_min=20,
                difficulty="Avanzato",
                summary="I miglioramenti utili partono da review precise, non da nervosismo operativo.",
                theory="Ogni modifica va motivata da un difetto osservato: troppi falsi segnali, news sensitivity, sizing fragile, perdita di edge in certi regimi. Le review periodiche servono a mantenere il sistema leggibile e migliorabile.",
                practical=["Scrivi sempre il problema prima della modifica.", "Collega ogni revisione a una metrica."],
                mistakes=["Cambiare il bot solo perché il mese è andato male."],
                app_links=[APP_CTA_WORKSPACE, APP_CTA_DESK],
            ),
            lesson(
                "iteration-experiment-tracking",
                "Tracking degli esperimenti",
                duration_min=18,
                difficulty="Intermedio",
                summary="Senza tracciamento, migliorare diventa solo confusione elegante.",
                theory="Ogni test deve avere ipotesi, modifica, risultato e decisione finale. Questo è ciò che distingue una pipeline professionale da una serie di prove casuali.",
                practical=["Usa project memory e versioni come journal di ricerca.", "Confronta prima/dopo in modo disciplinato."],
                mistakes=["Non sapere più quale modifica ha creato quale effetto."],
                app_links=[APP_CTA_WORKSPACE],
            ),
            lesson(
                "iteration-scaling",
                "Quando scalare, quando fermarsi",
                duration_min=16,
                difficulty="Avanzato",
                summary="Non tutto ciò che migliora un backtest merita più capitale o più complessità.",
                theory="A volte il miglior upgrade è fermarsi e non aggiungere nulla. Scalare un bot richiede stabilità, controllo rischio e governance, non solo un grafico più bello.",
                practical=["Aumenta capitale solo dopo stabilità sufficiente.", "Taglia complessità se non paga."],
                mistakes=["Confondere fit migliore con qualità superiore."],
                app_links=[APP_CTA_DESK],
            ),
        ],
    },
]


ACADEMY_FEATURES = [
    "Percorso progressivo da base a deploy",
    "Collegamenti diretti a builder, backtest e desk",
    "Libreria segnali pensata come enciclopedia operativa",
    "Progress tracking persistente per utente",
]


def get_academy_catalog() -> dict[str, Any]:
    return {
        "title": "Algorithmic Trading Academy",
        "description": "Formazione professionale per progettare, testare, migliorare e governare algoritmi MT5.",
        "academy_title": "Algorithmic Trading Academy",
        "academy_subtitle": "Formazione professionale per progettare, testare, migliorare e governare algoritmi MT5.",
        "modules": ACADEMY_MODULES,
        "indicator_library": INDICATOR_LIBRARY,
        "features": ACADEMY_FEATURES,
    }
